apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: myapp
  template:
   metadata:
    name: pod1
    labels: 
     app: myapp
   spec:
     containers:
       - name: c1
         image: nareshtechnologies/netflixv1
         ports:
          - containerPort: 80
            hostPort: 6666
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  selector:
    app: myapp
  ports:
    - targetPort: 80
      port: 80
