apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
     app: myapp
  template:
   metadata:
    name: pod1
    labels: 
     app: myapp
   spec:
     containers:
       - name: c1
         image: nareshtechnologies/netflix:v1
         ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector: 
    app: myapp
  ports:
    - targetPort: 80
      nodePort: 32000
      port: 80


    
  
