apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: c1
          image: nareshtechnologies/netflixv1
          ports:
            - containerPort: 80  # Expose port 80 inside the container (no need for hostPort)
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer  # Exposing service via LoadBalancer
  selector:
    app: myapp  # This should match the label of your pods (app: myapp)
  ports:
    - port: 80      # External port for the LoadBalancer
      targetPort: 80 # Internal container port where the app listens
